export default [
  "The 'weapons-grade' Dragon's Breath chili pepper is so hot it's downright deadly. If you ate one, it could potentially cause a type of anaphylactic shock.",
  "Babies can't differentiate between dreams and reality. Their brains literally don't have the circuitry yet, all the way until they're about two years old.",
  "More French soldiers died during World War 1 than American soldiers during the entire US military history, including both sides of the civil war.",
  "Anne Frank and Martin Luther King Jr. were born in the same year but if you were to say their names to someone, they would think of completely different moments in history.",
  "There are more uncontacted people in Brazil's portion of the Amazon than anywhere else on the planet, with the number of isolated tribes believed to be more than 100.",
  "The Yoruba people in the southwest part of Nigeria are known for giving birth to more twins than anywhere else in the world, at a rate of 50 per 1,000 births.",
  "Tea is big in the United Kingdom, locals reportedly drink 165 million cups a day. But it was a Portugeuse woman who first brought the drink to the isles.",
  "Mount Everest was first measured in 1856 at 8,840m tall. The height was then adjusted to 8,848m in 1955, which is still the official height stated by the Nepalese government.",
  "Temperatures vary across the Pacific Ocean. The closer to the equator the warmer the water's temperatures. Water near the poles reaches the freezing point!",
  "Geological activity and erosion by the Colorado River created the Grand Canyon as we know it today. It is one of the most studied landscapes in the world.",
  "Grand Canyon National Park, a world heritage site, belongs to everyone. Rocks, plants, wood and artifacts must be left where you found them so others can enjoy them.",
  "The Grand Canyon is home to about 1000 caves, but only 335 have been explored and recorded. Likewise, only a few of the caves at the Grand Canyon have been mapped.",
  "The North Pole has no land mass at all. Instead, it is made up of huge ice floes, 6 to 10 feet thick, that float on the surface of the Arctic Ocean.",
  "The word 'Pacific' means peaceful. The Pacific Ocean got its name from the explorer Ferdinand Magellan. He called the ocean “mar pacific”, which meant peaceful sea.",
  "The first successful summit of Mount Everest was recorded on May 29, 1953 by Sir Edmund Hillary from New Zealand. He was accompanied by Tenzing Norgay, a Sherpa from Nepal.",
  "Bread was invented in Egypt around 8,000 BC. The first examples of it were flat and unleavened, most closely resembling what we know today as tortillas in Latin America.",
  "In 2007, two Russian submarines embarked on a record-breaking dive to the seabed of the North Pole, two and a half miles beneath the surface of the Arctic Ocean.",
  "Over the past 50 years, average temperatures across the Antarctic Peninsula have increased by 3 degree celsius, five times the average increase on Earth.",
  "Although Jupiter and Saturn are typically known for their moons, Uranus also has a good amount of it. There are 27 confirmed moons that are orbiting the big blue planet.",
  "The wolverine has one large tooth that points towards the back of its throat that, when combined with the wolverine's jaw muscles, can snap a moose femur in half.",
  "The giant squid's brain is a torus shape, and its esophagus runs through it. If the squid eats anything too big, it will suffer massive brain damage.",
  "Venus rotates on its axis only once every 243 Earth days but orbits the sun once every 224.65 Earth days. This means that on Venus, a day is longer than a year.",
  "On the antipode of Mecca, there is an island with a Muslim population. They can choose which direction to pray, because all directions are towards Mecca.",
];
